### ISSUE TITLE
Telemetry ssr INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by MSkred** [nuxt/telemetry#18]
I've accepted in the console terminal telemetry collect, and now when I deploy my website on my AWS Lambda I've this logs 

    "nuxt": "^2.12.2",

```
  | 2020-06-25T16:20:10.258+02:00 | FATAL ENOENT: no such file or directory, open '/home/sbx_user1051/.nuxtrc'

  | 2020-06-25T16:25:25.052+02:00 | 2020-06-25T14:25:25.052Z	95118a2c-c4e6-4755-9774-af52c02703ef	ERROR	{ Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.nuxtrc'    at Object.openSync (fs.js:443:3)    at Object.writeFileSync (fs.js:1194:35)    at write (/var/task/node_modules/rc9/dist/index.js:87:6)    at update (/var/task/node_modules/rc9/dist/index.js:106:3)    at Object.updateUser (/var/task/node_modules/rc9/dist/index.js:112:10)    at updateUserNuxtRc (/var/task/node_modules/@nuxt/telemetry/dist/module.js:30:6)    at ModuleContainer.telemetryModule (/var/task/node_modules/@nuxt/telemetry/dist/module.js:511:5)  errno: -2,  syscall: 'open',  code: 'ENOENT',  path: '/home/sbx_user1051/.nuxtrc' }
-- | -- | --
-- | -- | --
  | 2020-06-25T16:20:10.258+02:00 | at Object.openSync (fs.js:443:3)
  | 2020-06-25T16:20:10.258+02:00 | at Object.writeFileSync (fs.js:1194:35)
  | 2020-06-25T16:20:10.258+02:00 | at write (node_modules/rc9/dist/index.js:87:6)
  | 2020-06-25T16:20:10.258+02:00 | at update (node_modules/rc9/dist/index.js:106:3)
  | 2020-06-25T16:20:10.258+02:00 | at Object.updateUser (node_modules/rc9/dist/index.js:112:10)
  | 2020-06-25T16:20:10.258+02:00 | at updateUserNuxtRc (node_modules/@nuxt/telemetry/dist/module.js:30:6)
  | 2020-06-25T16:20:10.258+02:00 | at ModuleContainer.telemetryModule (node_modules/@nuxt/telemetry/dist/module.js:511:5)
```

And an internal server error on my website https://beta-admin.staging.letsgocity.be/

**Comment by micheldenegri** [comment]
I'm getting the same error in a vercel hosted app after we upgraded our nuxt version to `2.13.1`. During our CI build process we do create a project level `.nuxtrc` file. I use the `@nuxtjs/now-builder` to deploy our app.

```
2020-06-26T00:22:19.079Z	undefined	ERROR	λ Error while initializing nuxt: Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.nuxtrc'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1279:35)
    at write (/var/task/node_modules/rc9/dist/index.js:87:6)
    at update (/var/task/node_modules/rc9/dist/index.js:106:3)
    at Object.updateUser (/var/task/node_modules/rc9/dist/index.js:112:10)
    at updateUserNuxtRc (/var/task/node_modules/@nuxt/telemetry/dist/module.js:30:6)
    at ModuleContainer.telemetryModule (/var/task/node_modules/@nuxt/telemetry/dist/module.js:511:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ModuleContainer.addModule (/var/task/node_modules/@nuxt/core/dist/core.js:223:20) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/sbx_user1051/.nuxtrc'
}
```
 It looks like telemetry cant access the home directory when trying to check for that global `.nuxtrc` file, not sure why, maybe due to the fact home dir is not writable or `os.homedir()` is resolving to a directory that does not exists?

**Comment by micheldenegri** [comment]
I got it to work by setting `telemetry` option in the `nuxt.config.js` or by setting the environment variable `NUXT_TELEMETRY_DISABLED`, not sure why the project level `.nuxtrc` didn't work or maybe I need to add that to the now.json `config.serverFiles`.

**Comment by MSkred** [comment]
I fixed this with :

1. nuxt 2.13.1
2. rm -rf node_modules/
3. yarn install
4. yarn upgrade
5. telemetry : false into nuxt.config.js
